// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reviews;

namespace Reviews.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190620173647_FifthMigration")]
    partial class FifthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reviews.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Reviews.Model.HorrorReviews", b =>
                {
                    b.Property<int>("HorrorReviewsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("MovieId");

                    b.HasKey("HorrorReviewsId");

                    b.HasIndex("MovieId");

                    b.ToTable("HorrorReviews");

                    b.HasData(
                        new { HorrorReviewsId = 1, Content = "This is a great family movie, recommend you bring the kids, especially the young ones!Full of laughs, and life lessons too. As soon as we got out of the theatre, my six year old wanted to see it again!", MovieId = 1 },
                        new { HorrorReviewsId = 2, Content = "King Lear", MovieId = 1 }
                    );
                });

            modelBuilder.Entity("Reviews.Model.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new { MovieId = 1, Description = "1999 American supernatural horror film written, directed and edited by Daniel Myrick Eduardo Sanchez.", ImageUrl = "BlairWitch.jpg", Title = "Blair Witch Project" },
                        new { MovieId = 2, Description = "2018 American psychological horror drama film written and directed by  Ari Aster.", ImageUrl = "Hereditary.jpg", Title = "Hereditary" },
                        new { MovieId = 3, Description = "2004 American psychological horror-thriller filmed and directed by James Wan.", ImageUrl = "Saw.jpg", Title = "Saw" },
                        new { MovieId = 4, Description = "1982 science fiction horror film directed by John Carpenter.", ImageUrl = "TheThing.jpg", Title = "The Thing" },
                        new { MovieId = 5, Description = "War of the Worlds, 2005 American science-fiction action film directed by Steven Spielberg and written by Josh Friedman and David Koepp, loosely based on the 1898 novel of the same title by H. G. Wells", ImageUrl = "WarofWorlds.jpg", Title = "War of the Worlds" },
                        new { MovieId = 6, Description = "1997 film. In 2047 a group of astronauts are sent to investigate and salvage the starship ‘Event Horizon’ which disappeared mysteriously 7 years before on its maiden voyage. With its return, the crew of the ‘Lewis and Clark’ discovers the real truth behind the disappearance of the ‘Event Horizon’ – and something even more terrifying.", ImageUrl = "EventHorizon.jpg", Title = "Event Horizon" },
                        new { MovieId = 7, Description = "1974 film, Five friends visiting their grandfather’s house in the country are hunted and terrorized by a chain-saw wielding killer and his family of grave-robbing cannibals.", ImageUrl = "TexasChainsaw.jpg", Title = "Texas Chainsaw Massacre" },
                        new { MovieId = 8, Description = "2012 American horror comedy film directed by Drew Goddard in his directorial debut, produced by Joss Whedon, and written by Whedon and Goddard.", ImageUrl = "CabinInWoods.png", Title = "Cabin in the Woods" },
                        new { MovieId = 9, Description = "2007 film. After a young, middle class couple moves into a suburban ‘starter’ tract house, they become increasingly disturbed by a presence that may or may not be somehow demonic but is certainly most active in the middle of the night. Especially when they sleep. Or try to.", ImageUrl = "ParanormalActivity.jpg", Title = "Paranormal Activity" }
                    );
                });

            modelBuilder.Entity("Reviews.Model.HorrorReviews", b =>
                {
                    b.HasOne("Reviews.Model.Movie", "ReviewMovie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Reviews.Model.Movie", b =>
                {
                    b.HasOne("Reviews.Model.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
